# Generated by Django 3.2.3 on 2022-07-02 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('categoria', models.CharField(max_length=32)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('nombreproductor', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Nombre del productor')),
                ('telefonoproductor', models.IntegerField(verbose_name='Telefono del productor')),
            ],
            options={
                'verbose_name': 'Productor',
                'verbose_name_plural': 'Productores',
                'db_table': 'productor',
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('idtransporte', models.BigAutoField(primary_key=True, serialize=False)),
                ('nomtransporte', models.CharField(max_length=250, verbose_name='Nombre Empresa Transporte')),
                ('preciotransporte', models.IntegerField(verbose_name='Precio del transporte')),
            ],
            options={
                'verbose_name': 'Transporte',
                'verbose_name_plural': 'Transportes',
                'db_table': 'transporte',
            },
        ),
        migrations.CreateModel(
            name='ProductoStock',
            fields=[
                ('idproductostock', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=64)),
                ('categoria', models.CharField(max_length=32)),
                ('precio', models.IntegerField()),
                ('nombreproductor', models.ForeignKey(db_column='nombreproductor', on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.transporte', verbose_name='Productor')),
            ],
            options={
                'verbose_name': 'Producto en Stock',
                'verbose_name_plural': 'Productos en Stock',
                'db_table': 'productosStock',
            },
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('iddespacho', models.BigAutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=64)),
                ('comuna', models.CharField(max_length=32)),
                ('estadodespacho', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptado', 'Aceptado'), ('Empacado', 'Empacado'), ('En camino', 'En camino'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=50, verbose_name='Estado del despacho')),
                ('nombrereceptor', models.CharField(max_length=64, verbose_name='Nombre de quien recibe el la compra')),
                ('fechacompra', models.DateTimeField(auto_now_add=True, verbose_name='Fecha generación despacho')),
                ('idtransporte', models.ForeignKey(db_column='idtransporte', on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.transporte', verbose_name='Empresa de transporte')),
            ],
            options={
                'verbose_name': 'Despacho',
                'verbose_name_plural': 'Despachos',
                'db_table': 'despacho',
            },
        ),
    ]
