# Generated by Django 3.2.3 on 2022-07-02 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20220618_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('idireccion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=64)),
                ('comuna', models.CharField(max_length=32)),
            ],
        ),
    ]
