# Generated by Django 3.2.3 on 2022-07-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='idireccion',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
