# Generated by Django 3.2.3 on 2022-07-02 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_direccion_idireccion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Direccion',
            new_name='Despacho',
        ),
        migrations.RenameField(
            model_name='despacho',
            old_name='idireccion',
            new_name='iddespacho',
        ),
    ]
