# Generated by Django 3.2.3 on 2022-06-17 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipousuario',
            fields=[
                ('idtipousuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('nomtipousuario', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipousuario',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('correousuario', models.CharField(max_length=200)),
                ('contrasenausuario', models.CharField(max_length=20)),
                ('nomusuario', models.CharField(max_length=100)),
                ('apellidosusuario', models.CharField(max_length=500)),
                ('estadousuario', models.CharField(blank=True, max_length=100, null=True)),
                ('fecharegistrousuario', models.DateField(blank=True, null=True)),
                ('idtipousuario', models.ForeignKey(db_column='idtipousuario', on_delete=django.db.models.deletion.CASCADE, to='core.tipousuario')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
