# Generated by Django 3.2.3 on 2022-06-11 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('idalimento', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nomalimento', models.CharField(max_length=100)),
                ('codalimento', models.CharField(blank=True, max_length=100, null=True)),
                ('pesoalimento', models.DecimalField(blank=True, decimal_places=1, max_digits=38, null=True)),
            ],
            options={
                'db_table': 'alimento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('idcompra', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fechacompra', models.DateField(blank=True, null=True)),
                ('fechaestadocompra', models.DateField()),
                ('numcompra', models.BigIntegerField()),
                ('totalcompra', models.BigIntegerField()),
                ('estadocompra', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('iddespacho', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nomdespacho', models.CharField(blank=True, max_length=250, null=True)),
                ('fechainicdespacho', models.DateField(blank=True, null=True)),
                ('fechafindespacho', models.DateField(blank=True, null=True)),
                ('estadodespacho', models.CharField(blank=True, max_length=250, null=True)),
                ('direcciondespacho', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'despacho',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detallecompra',
            fields=[
                ('iddetallecompra', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cantidadcompra', models.BigIntegerField()),
                ('preciocompra', models.BigIntegerField()),
            ],
            options={
                'db_table': 'detallecompra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detalleventa',
            fields=[
                ('iddetalleventa', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cantidaddetalleventa', models.BigIntegerField()),
                ('precioventa', models.BigIntegerField()),
                ('descuentoventa', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detalleventa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idempleado', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nomempleado', models.CharField(max_length=150)),
                ('apmaternoemp', models.CharField(max_length=150)),
                ('appaternoemp', models.CharField(max_length=150)),
                ('rutemp', models.BigIntegerField()),
                ('dvrutemp', models.CharField(max_length=1)),
                ('direccionemp', models.CharField(max_length=250)),
                ('correoemp', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('idinventario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fechainventario', models.DateField(blank=True, null=True)),
                ('nominventario', models.CharField(blank=True, max_length=250, null=True)),
                ('conteoinventario', models.BigIntegerField(blank=True, null=True)),
                ('precioconteoinventario', models.DecimalField(blank=True, decimal_places=2, max_digits=38, null=True)),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idproveedor', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nomproveedor', models.CharField(max_length=150)),
                ('telefproveedor', models.IntegerField(blank=True, null=True)),
                ('celuproveedor', models.IntegerField(blank=True, null=True)),
                ('direccionproveedor', models.CharField(blank=True, max_length=500, null=True)),
                ('rutproveedor', models.BigIntegerField()),
                ('dvrutproveedor', models.BigIntegerField()),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoalimento',
            fields=[
                ('idtipoalimento', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nomtipoalimento', models.CharField(max_length=150)),
                ('codtipoalimento', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'tipoalimento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoempleado',
            fields=[
                ('idtipoempleado', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nomtipoempleado', models.CharField(max_length=250)),
                ('salariotipoempleado', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipoempleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoproveedor',
            fields=[
                ('idtipoproveedor', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nomtipoproveedor', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'tipoproveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipousuario',
            fields=[
                ('idtipousuario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nomtipousuario', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipousuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('idtransporte', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nomtransporte', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'transporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('correousuario', models.CharField(max_length=200)),
                ('contrasenausuario', models.CharField(max_length=20)),
                ('nomusuario', models.CharField(max_length=100)),
                ('apellidosusuario', models.CharField(max_length=500)),
                ('estadousuario', models.CharField(blank=True, max_length=100, null=True)),
                ('fecharegistrousuario', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idventa', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fechaventa', models.DateField()),
                ('numventa', models.BigIntegerField()),
                ('totalventa', models.BigIntegerField(blank=True, null=True)),
                ('estadoventa', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlmtoInv',
            fields=[
                ('idalimento', models.OneToOneField(db_column='idalimento', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.alimento')),
            ],
            options={
                'db_table': 'almto_inv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpInv',
            fields=[
                ('idempleado', models.OneToOneField(db_column='idempleado', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.empleado')),
            ],
            options={
                'db_table': 'emp_inv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProveAlmto',
            fields=[
                ('idproveedor', models.OneToOneField(db_column='idproveedor', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.proveedor')),
            ],
            options={
                'db_table': 'prove_almto',
                'managed': False,
            },
        ),
    ]
