# Generated by Django 3.2.3 on 2022-06-17 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('idalimento', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nomalimento', models.CharField(max_length=100)),
                ('codalimento', models.CharField(blank=True, max_length=100, null=True)),
                ('pesoalimento', models.DecimalField(blank=True, decimal_places=1, max_digits=38, null=True)),
            ],
            options={
                'db_table': 'alimento',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('idcompra', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fechacompra', models.DateField(blank=True, null=True)),
                ('fechaestadocompra', models.DateField()),
                ('numcompra', models.BigIntegerField()),
                ('totalcompra', models.BigIntegerField()),
                ('estadocompra', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'compra',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idempleado', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nomempleado', models.CharField(max_length=150)),
                ('apmaternoemp', models.CharField(max_length=150)),
                ('appaternoemp', models.CharField(max_length=150)),
                ('rutemp', models.BigIntegerField()),
                ('dvrutemp', models.CharField(max_length=1)),
                ('direccionemp', models.CharField(max_length=250)),
                ('correoemp', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('idinventario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fechainventario', models.DateField(blank=True, null=True)),
                ('nominventario', models.CharField(blank=True, max_length=250, null=True)),
                ('conteoinventario', models.BigIntegerField(blank=True, null=True)),
                ('precioconteoinventario', models.DecimalField(blank=True, decimal_places=2, max_digits=38, null=True)),
            ],
            options={
                'db_table': 'inventario',
            },
        ),
        migrations.CreateModel(
            name='Tipoalimento',
            fields=[
                ('idtipoalimento', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nomtipoalimento', models.CharField(max_length=150)),
                ('codtipoalimento', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'tipoalimento',
            },
        ),
        migrations.CreateModel(
            name='Tipoempleado',
            fields=[
                ('idtipoempleado', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nomtipoempleado', models.CharField(max_length=250)),
                ('salariotipoempleado', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipoempleado',
            },
        ),
        migrations.CreateModel(
            name='Tipoproveedor',
            fields=[
                ('idtipoproveedor', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nomtipoproveedor', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'tipoproveedor',
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idtipousuario',
            field=models.ForeignKey(db_column='idtipousuario', on_delete=django.db.models.deletion.DO_NOTHING, to='core.tipousuario'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idventa', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fechaventa', models.DateField()),
                ('numventa', models.BigIntegerField()),
                ('totalventa', models.BigIntegerField(blank=True, null=True)),
                ('estadoventa', models.CharField(max_length=100)),
                ('idempleado', models.ForeignKey(db_column='idempleado', on_delete=django.db.models.deletion.DO_NOTHING, to='core.empleado')),
            ],
            options={
                'db_table': 'venta',
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('idtransporte', models.BigAutoField(primary_key=True, serialize=False)),
                ('nomtransporte', models.CharField(max_length=250)),
                ('idempleado', models.ForeignKey(db_column='idempleado', on_delete=django.db.models.deletion.DO_NOTHING, to='core.empleado')),
            ],
            options={
                'db_table': 'transporte',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idproveedor', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nomproveedor', models.CharField(max_length=150)),
                ('telefproveedor', models.IntegerField(blank=True, null=True)),
                ('celuproveedor', models.IntegerField(blank=True, null=True)),
                ('direccionproveedor', models.CharField(blank=True, max_length=500, null=True)),
                ('rutproveedor', models.BigIntegerField()),
                ('dvrutproveedor', models.BigIntegerField()),
                ('idtipoproveedor', models.ForeignKey(db_column='idtipoproveedor', on_delete=django.db.models.deletion.DO_NOTHING, to='core.tipoproveedor')),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='idtipoempleado',
            field=models.ForeignKey(db_column='idtipoempleado', on_delete=django.db.models.deletion.DO_NOTHING, to='core.tipoempleado'),
        ),
        migrations.CreateModel(
            name='Detalleventa',
            fields=[
                ('iddetalleventa', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cantidaddetalleventa', models.BigIntegerField()),
                ('precioventa', models.BigIntegerField()),
                ('descuentoventa', models.BigIntegerField(blank=True, null=True)),
                ('idalimento', models.ForeignKey(db_column='idalimento', on_delete=django.db.models.deletion.DO_NOTHING, to='core.alimento')),
                ('idventa', models.ForeignKey(db_column='idventa', on_delete=django.db.models.deletion.DO_NOTHING, to='core.venta')),
            ],
            options={
                'db_table': 'detalleventa',
            },
        ),
        migrations.CreateModel(
            name='Detallecompra',
            fields=[
                ('iddetallecompra', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cantidadcompra', models.BigIntegerField()),
                ('preciocompra', models.BigIntegerField()),
                ('idalimento', models.ForeignKey(db_column='idalimento', on_delete=django.db.models.deletion.DO_NOTHING, to='core.alimento')),
                ('idcompra', models.ForeignKey(db_column='idcompra', on_delete=django.db.models.deletion.DO_NOTHING, to='core.compra')),
                ('idproveedor', models.ForeignKey(db_column='idproveedor', on_delete=django.db.models.deletion.DO_NOTHING, to='core.proveedor')),
            ],
            options={
                'db_table': 'detallecompra',
            },
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('iddespacho', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nomdespacho', models.CharField(blank=True, max_length=250, null=True)),
                ('fechainicdespacho', models.DateField(blank=True, null=True)),
                ('fechafindespacho', models.DateField(blank=True, null=True)),
                ('estadodespacho', models.CharField(blank=True, max_length=250, null=True)),
                ('direcciondespacho', models.CharField(blank=True, max_length=250, null=True)),
                ('idtransporte', models.ForeignKey(db_column='idtransporte', on_delete=django.db.models.deletion.DO_NOTHING, to='core.transporte')),
                ('idventa', models.ForeignKey(blank=True, db_column='idventa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.venta')),
            ],
            options={
                'db_table': 'despacho',
            },
        ),
        migrations.AddField(
            model_name='alimento',
            name='idtipoalimento',
            field=models.ForeignKey(db_column='idtipoalimento', on_delete=django.db.models.deletion.DO_NOTHING, to='core.tipoalimento'),
        ),
        migrations.CreateModel(
            name='ProveAlmto',
            fields=[
                ('idproveedor', models.OneToOneField(db_column='idproveedor', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.proveedor')),
                ('idalimento', models.ForeignKey(db_column='idalimento', on_delete=django.db.models.deletion.DO_NOTHING, to='core.alimento')),
            ],
            options={
                'db_table': 'prove_almto',
                'unique_together': {('idproveedor', 'idalimento')},
            },
        ),
        migrations.CreateModel(
            name='EmpInv',
            fields=[
                ('idempleado', models.OneToOneField(db_column='idempleado', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.empleado')),
                ('idinventario', models.ForeignKey(db_column='idinventario', on_delete=django.db.models.deletion.DO_NOTHING, to='core.inventario')),
            ],
            options={
                'db_table': 'emp_inv',
                'unique_together': {('idempleado', 'idinventario')},
            },
        ),
        migrations.CreateModel(
            name='AlmtoInv',
            fields=[
                ('idalimento', models.OneToOneField(db_column='idalimento', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.alimento')),
                ('idinventario', models.ForeignKey(db_column='idinventario', on_delete=django.db.models.deletion.DO_NOTHING, to='core.inventario')),
            ],
            options={
                'db_table': 'almto_inv',
                'unique_together': {('idalimento', 'idinventario')},
            },
        ),
    ]
