# Generated by Django 3.2.3 on 2022-07-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220630_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporte',
            name='idempleado',
        ),
        migrations.AlterField(
            model_name='transporte',
            name='nomtransporte',
            field=models.CharField(max_length=250, verbose_name='Nombre Transporte'),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='preciotransporte',
            field=models.IntegerField(verbose_name='Precio del transporte'),
        ),
    ]
