# Generated by Django 3.2.3 on 2022-06-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220618_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='precioalimento',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
