# Generated by Django 3.2.3 on 2022-06-18 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alimento_precioalimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contrasenausuario',
            new_name='Contraseña',
        ),
    ]
