# Generated by Django 3.2.3 on 2022-06-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220618_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproveedor',
            name='idtipoproveedor',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
